### PR TITLE
Stamina/Fatigue Refactor

### PR DESCRIPTION
**Pull request by V2LenKagamine**
## About The Pull Request
Technical Details:
-Swaps Fatigue and Stamina, and most if not all references of such
-Stamina is now something that drains rather than goes up with actions.
-Renames No rogstam to no fatigue, as its now fatigue anyway

Balance/bugfixes:
-Health potions now heal half as much per tick, but last longer.
-"Mana" potions heal fatigue, because no mana
-Stamina potions/poisons now heal/damage stamina, instead of being accidental copies of Mana potions
## Why It's Good For The Game

Aberra request and blue should not be stamina in any game like ever.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by dwasint** [comment]
this is just getting closed the systems are not interchangeable and this will just lead to far to many things breaking over time.

**Comment by dwasint** [comment]
it also would make accidental errors from porting features from other codebases 100x more common

**Comment by V2LenKagamine** [comment]
> it also would make accidental errors from porting features from other codebases 100x more common

I can kinda see that, but it also means that we live with the shitcode of them being backwards forever. Its better to bite the bullet and fix it now rather than leave technical debt for later and have to teach everyone that the green bar is "Fatigue" and the blue bar is "Stamina"

**Comment by V2LenKagamine** [comment]
No to mention: This is a direct aberra request to make them not backwards like that. Its in the common mind that stamina is Green and Fatigue/mana is blue, so with not merging this we're confusing new players over a system that could be logical

**Pull request closed without merging**
